### ISSUE TITLE
crash when closing multiple tabs

### ISSUE THREAD

**Issue by droumis** [magland/mountainlab#116] opened 2016-12-09 19:10 UTC
command line output:

===== QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running

===== QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running

===== QThread: Destroyed while thread is still running

===== Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

QThread: Destroyed while thread is still running

===== Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

===== Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

**Comment by magland** [comment] 2016-12-09 19:20
Someone else reported this but was unable to reproduce systematically.

Are you able to reproduce?

**Comment by droumis** [comment] 2016-12-09 20:14
Yes, I just reproduced it. It crashed after closing 3 tabs in quick succession. output:  

`


---- Computing PCA features...


===== QThread: Destroyed while thread is still running


===== Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.
`

**Comment by magland** [comment] 2016-12-12 15:28
Having trouble reproducing on our end. (We do experience a crash related to spikespray, but I think it is a different issue). Which view are you closing three times in succession? Does it matter whether it is still computing when you close it?

**Closed** 2017-07-14 12:25 UTC
